#!/usr/bin/env python3
"""
NEXUS CALENDAR AUTOMATION SYSTEM
Auto-generate calendar files and track deadlines

Created: January 28, 2026
Priority: CRITICAL (after Alaska bid was missed)
"""

import os
from datetime import datetime, timedelta
from typing import Dict, List, Optional
from dotenv import load_dotenv
from pyairtable import Api
from icalendar import Calendar, Event, Alarm
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

# Load environment variables
load_dotenv()


class CalendarAutomation:
    """
    Automated calendar generation and deadline tracking for NEXUS
    
    Prevents missed deadlines by:
    1. Auto-generating .ics calendar files for all opportunities
    2. Emailing calendar files to user
    3. Calculating supplier quote deadlines
    4. Sending daily deadline reports
    5. Alerting for urgent deadlines
    """
    
    def __init__(self):
        """Initialize with Airtable and email credentials"""
        self.airtable_token = os.environ.get('AIRTABLE_API_KEY')
        self.base_id = os.environ.get('AIRTABLE_BASE_ID')
        self.api = Api(self.airtable_token)
        
        # Email settings
        self.email_from = os.environ.get('NEXUS_EMAIL')
        self.email_password = os.environ.get('NEXUS_EMAIL_PASSWORD')
        self.email_to = os.environ.get('USER_EMAIL', 'info@deedavis.biz')
        
        # Calendar file directory
        self.calendar_dir = '/Users/deedavis/NEXUS BACKEND/calendars'
        os.makedirs(self.calendar_dir, exist_ok=True)
    
    def generate_opportunity_calendar(self, opportunity_record: Dict) -> str:
        """
        Generate .ics calendar file for an opportunity
        
        Args:
            opportunity_record: Airtable record with opportunity data
            
        Returns:
            Path to generated .ics file
        """
        fields = opportunity_record['fields']
        record_id = opportunity_record['id']
        
        # Extract key information
        title = fields.get('Name', 'Untitled Opportunity')
        deadline = fields.get('Deadline')
        agency = fields.get('Agency Name', '')
        solicitation_num = fields.get('Solicitation Number', '')
        
        if not deadline:
            print(f"⚠️  No deadline for {title} - skipping calendar generation")
            return None
        
        # Parse deadline
        try:
            deadline_dt = datetime.strptime(deadline, '%Y-%m-%d')
        except ValueError:
            try:
                deadline_dt = datetime.strptime(deadline, '%m/%d/%Y')
            except ValueError:
                print(f"❌ Could not parse deadline: {deadline}")
                return None
        
        # Create calendar
        cal = Calendar()
        cal.add('prodid', '-//DEE DAVIS INC//NEXUS//EN')
        cal.add('version', '2.0')
        
        # Create event
        event = Event()
        event.add('summary', f'🚨 BID DEADLINE: {title}')
        event.add('dtstart', deadline_dt)
        event.add('dtend', deadline_dt + timedelta(hours=1))
        event.add('dtstamp', datetime.now())
        
        # Description with all details
        description = f"""
🚨 BID DEADLINE

Opportunity: {title}
Agency: {agency}
Solicitation: {solicitation_num}
Deadline: {deadline_dt.strftime('%B %d, %Y at %I:%M %p')}

AIRTABLE RECORD: https://airtable.com/{self.base_id}/{record_id}

⏰ REMINDERS SET:
- 7 days before
- 3 days before
- 1 day before
- Morning of deadline
- 2 hours before deadline

🎯 ACTION ITEMS:
1. Send supplier quote requests (3-5 days before)
2. Collect all quotes (2 days before)
3. Complete bid forms (1 day before)
4. Final review (morning of deadline)
5. SUBMIT (before deadline!)

Generated by NEXUS Calendar Automation
        """.strip()
        
        event.add('description', description)
        event.add('location', agency)
        event.add('uid', f'{record_id}@nexus.deedavis.biz')
        
        # Add reminders
        reminders = [
            timedelta(days=7),    # 7 days before
            timedelta(days=3),    # 3 days before
            timedelta(days=1),    # 1 day before
            timedelta(hours=2),   # 2 hours before
        ]
        
        for reminder_delta in reminders:
            alarm = Alarm()
            alarm.add('action', 'DISPLAY')
            alarm.add('trigger', -reminder_delta)
            alarm.add('description', f'BID DEADLINE: {title}')
            event.add_component(alarm)
        
        cal.add_component(event)
        
        # Save to file
        safe_title = "".join(c for c in title if c.isalnum() or c in (' ', '-', '_')).rstrip()
        safe_title = safe_title.replace(' ', '_').lower()[:50]
        filename = f"{safe_title}_{deadline_dt.strftime('%Y-%m-%d')}.ics"
        filepath = os.path.join(self.calendar_dir, filename)
        
        with open(filepath, 'wb') as f:
            f.write(cal.to_ical())
        
        print(f"✅ Generated calendar file: {filename}")
        return filepath
    
    def calculate_quote_deadline(self, bid_deadline: str, days_before: int = 3) -> str:
        """
        Calculate when supplier quotes are due
        
        Args:
            bid_deadline: Bid deadline date (YYYY-MM-DD or MM/DD/YYYY)
            days_before: Days before bid deadline (default: 3)
            
        Returns:
            Quote deadline date string
        """
        try:
            bid_dt = datetime.strptime(bid_deadline, '%Y-%m-%d')
        except ValueError:
            bid_dt = datetime.strptime(bid_deadline, '%m/%d/%Y')
        
        quote_dt = bid_dt - timedelta(days=days_before)
        return quote_dt.strftime('%Y-%m-%d')
    
    def email_calendar_file(self, filepath: str, opportunity_name: str, deadline: str):
        """
        Email calendar file to user
        
        Args:
            filepath: Path to .ics file
            opportunity_name: Name of opportunity
            deadline: Deadline date
        """
        try:
            # Create message
            msg = MIMEMultipart()
            msg['From'] = self.email_from
            msg['To'] = self.email_to
            msg['Subject'] = f"📅 New Deadline: {opportunity_name} - {deadline}"
            
            # Email body
            body = f"""
New bid deadline added to your calendar!

🚨 OPPORTUNITY: {opportunity_name}
📅 DEADLINE: {deadline}

The attached .ics calendar file includes:
✅ Deadline reminder
✅ Multiple alerts (7 days, 3 days, 1 day, 2 hours before)
✅ Action items checklist
✅ Direct link to Airtable record

TO ADD TO YOUR CALENDAR:
1. Download the attached .ics file
2. Double-click to open
3. Confirm import to Apple Calendar / Google Calendar / Outlook

Your calendar will now alert you before the deadline!

---
NEXUS Calendar Automation System
Never miss a deadline again!
            """.strip()
            
            msg.attach(MIMEText(body, 'plain'))
            
            # Attach .ics file
            with open(filepath, 'rb') as f:
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(f.read())
            
            encoders.encode_base64(part)
            part.add_header(
                'Content-Disposition',
                f'attachment; filename={os.path.basename(filepath)}'
            )
            msg.attach(part)
            
            # Send email
            server = smtplib.SMTP('smtp.gmail.com', 587)
            server.starttls()
            server.login(self.email_from, self.email_password)
            server.send_message(msg)
            server.quit()
            
            print(f"✅ Emailed calendar file to {self.email_to}")
            
        except Exception as e:
            print(f"❌ Failed to email calendar file: {e}")
    
    def get_upcoming_deadlines(self, days_ahead: int = 7) -> List[Dict]:
        """
        Get all upcoming deadlines from Airtable
        
        Args:
            days_ahead: Number of days to look ahead (default: 7)
            
        Returns:
            List of opportunities with upcoming deadlines
        """
        table = self.api.table(self.base_id, 'GPSS OPPORTUNITIES')
        
        # Get all opportunities with deadlines
        records = table.all()
        
        upcoming = []
        today = datetime.now().date()
        future_date = today + timedelta(days=days_ahead)
        
        for record in records:
            fields = record['fields']
            deadline_str = fields.get('Deadline')
            status = fields.get('Status', '')
            
            if not deadline_str or status in ['Closed', 'Lost', 'Won']:
                continue
            
            try:
                deadline_dt = datetime.strptime(deadline_str, '%Y-%m-%d').date()
            except ValueError:
                try:
                    deadline_dt = datetime.strptime(deadline_str, '%m/%d/%Y').date()
                except ValueError:
                    continue
            
            if today <= deadline_dt <= future_date:
                days_until = (deadline_dt - today).days
                upcoming.append({
                    'record': record,
                    'name': fields.get('Name', 'Untitled'),
                    'deadline': deadline_dt,
                    'days_until': days_until,
                    'agency': fields.get('Agency Name', ''),
                    'value': fields.get('Estimated Value', 0)
                })
        
        # Sort by deadline (soonest first)
        upcoming.sort(key=lambda x: x['deadline'])
        
        return upcoming
    
    def send_daily_deadline_report(self):
        """
        Send daily email with upcoming deadlines
        Should be run every morning at 7 AM via cron
        """
        upcoming = self.get_upcoming_deadlines(days_ahead=14)
        
        if not upcoming:
            print("✅ No upcoming deadlines in next 14 days")
            return
        
        # Categorize by urgency
        urgent = [opp for opp in upcoming if opp['days_until'] <= 3]
        this_week = [opp for opp in upcoming if 3 < opp['days_until'] <= 7]
        next_week = [opp for opp in upcoming if 7 < opp['days_until'] <= 14]
        
        # Build email body
        body = "📋 NEXUS DAILY DEADLINE REPORT\n"
        body += f"{datetime.now().strftime('%A, %B %d, %Y')}\n\n"
        
        if urgent:
            body += "🔴 URGENT (Next 3 Days):\n"
            for opp in urgent:
                body += f"- {opp['name']}\n"
                body += f"  Deadline: {opp['deadline'].strftime('%B %d, %Y')} ({opp['days_until']} days)\n"
                body += f"  Agency: {opp['agency']}\n\n"
        
        if this_week:
            body += "🟡 THIS WEEK (4-7 Days):\n"
            for opp in this_week:
                body += f"- {opp['name']}\n"
                body += f"  Deadline: {opp['deadline'].strftime('%B %d, %Y')} ({opp['days_until']} days)\n"
                body += f"  Agency: {opp['agency']}\n\n"
        
        if next_week:
            body += "🟢 NEXT WEEK (8-14 Days):\n"
            for opp in next_week:
                body += f"- {opp['name']}\n"
                body += f"  Deadline: {opp['deadline'].strftime('%B %d, %Y')} ({opp['days_until']} days)\n"
                body += f"  Agency: {opp['agency']}\n\n"
        
        body += "\n---\nNEXUS Calendar Automation System\n"
        
        # Send email
        try:
            msg = MIMEMultipart()
            msg['From'] = self.email_from
            msg['To'] = self.email_to
            msg['Subject'] = f"📋 Daily Deadline Report - {len(upcoming)} Active Bids"
            msg.attach(MIMEText(body, 'plain'))
            
            server = smtplib.SMTP('smtp.gmail.com', 587)
            server.starttls()
            server.login(self.email_from, self.email_password)
            server.send_message(msg)
            server.quit()
            
            print(f"✅ Sent daily deadline report ({len(upcoming)} opportunities)")
            
        except Exception as e:
            print(f"❌ Failed to send daily report: {e}")
    
    def process_new_opportunities(self):
        """
        Check for new opportunities and generate calendar files
        Should be run hourly or when new opportunity is created
        """
        table = self.api.table(self.base_id, 'GPSS OPPORTUNITIES')
        
        # Get opportunities without calendar files
        # (Check for 'Calendar Generated' field or similar)
        records = table.all()
        
        processed = 0
        for record in records:
            fields = record['fields']
            
            # Skip if no deadline
            if not fields.get('Deadline'):
                continue
            
            # Generate calendar file (but DON'T email - emails handled by daily reports)
            filepath = self.generate_opportunity_calendar(record)
            
            if filepath:
                # NOTE: Not emailing individual files - this was causing Gmail to block us!
                # - 1,356 opportunities × hourly cron = 32,544 emails/day
                # - Gmail limit: 500-2,000/day
                # - Result: Account blocked
                #
                # Emails are now sent via:
                # - Daily deadline report (1 email/day)
                # - Urgent alerts (2-3/day)
                #
                # Individual calendar files are still generated for manual download
                processed += 1
        
        print(f"✅ Processed {processed} new opportunities")
        return processed


# Handler functions for NEXUS backend integration
def handle_generate_calendar(opportunity_id: str) -> Dict:
    """Generate calendar file for specific opportunity"""
    automation = CalendarAutomation()
    
    table = automation.api.table(automation.base_id, 'GPSS OPPORTUNITIES')
    record = table.get(opportunity_id)
    
    filepath = automation.generate_opportunity_calendar(record)
    
    if filepath:
        automation.email_calendar_file(
            filepath,
            record['fields'].get('Name'),
            record['fields'].get('Deadline')
        )
        
        return {
            'success': True,
            'filepath': filepath,
            'message': 'Calendar file generated and emailed'
        }
    else:
        return {
            'success': False,
            'message': 'Failed to generate calendar file'
        }


def handle_daily_deadline_report() -> Dict:
    """Send daily deadline report - run via cron at 7 AM"""
    automation = CalendarAutomation()
    automation.send_daily_deadline_report()
    
    return {'success': True, 'message': 'Daily report sent'}


def handle_process_new_opportunities() -> Dict:
    """Process new opportunities - run hourly via cron"""
    automation = CalendarAutomation()
    count = automation.process_new_opportunities()
    
    return {
        'success': True,
        'processed': count,
        'message': f'Processed {count} new opportunities'
    }


if __name__ == '__main__':
    """
    Test the calendar automation system
    """
    print("🚀 Testing NEXUS Calendar Automation System\n")
    
    automation = CalendarAutomation()
    
    # Test: Get upcoming deadlines
    print("📋 Checking upcoming deadlines...")
    upcoming = automation.get_upcoming_deadlines(days_ahead=30)
    print(f"Found {len(upcoming)} upcoming deadlines\n")
    
    for opp in upcoming[:5]:  # Show first 5
        print(f"- {opp['name']}")
        print(f"  Deadline: {opp['deadline']} ({opp['days_until']} days)")
        print(f"  Agency: {opp['agency']}\n")
    
    # Test: Send daily report
    print("\n📧 Sending daily deadline report...")
    automation.send_daily_deadline_report()
    
    print("\n✅ Calendar automation system ready!")
