#!/usr/bin/env python3
"""
FIX CALENDAR DEADLINES - Generate correct .ics files

Purpose: Create accurate calendar entries with correct dates AND times
Author: NEXUS System  
Created: February 5, 2026

This script generates calendar files with VERIFIED deadlines from official sources.
"""

import os
from datetime import datetime, timedelta

# Master list of VERIFIED deadlines (from official PDFs)
VERIFIED_BIDS = [
    {
        "bid_id": "RCOC 7732",
        "name": "Disposable Paper Products",
        "deadline": datetime(2026, 2, 10, 14, 30),  # 2:30 PM EST
        "value": "$81,478",
        "profit": "$3-5K",
        "status": "Ready to submit",
        "buyer": "Shari Graves (248-858-4780)",
        "platform": "BidNet Direct (MITN)",
        "filename": "rcoc_7732_paper_products_CORRECT_2026-02-10.ics"
    },
    {
        "bid_id": "RCOC 7842",
        "name": "Safety Supplies",
        "deadline": datetime(2026, 2, 17, 14, 30),  # 2:30 PM EST
        "value": "$31,558",
        "profit": "$3,975",
        "status": "Ready to submit",
        "buyer": "Shari Graves (248-858-4780)",
        "platform": "BidNet Direct (MITN)",
        "filename": "rcoc_7842_safety_supplies_CORRECT_2026-02-17.ics"
    },
    {
        "bid_id": "RCOC 7814",
        "name": "Pickup Trucks (16 units)",
        "deadline": datetime(2026, 2, 17, 14, 30),  # 2:30 PM EST
        "value": "$640K-$800K",
        "profit": "$80K-$120K",
        "status": "Awaiting dealer quotes",
        "buyer": "Shari Graves (248-858-4796)",
        "platform": "BidNet Direct (MITN)",
        "filename": "rcoc_7814_pickup_trucks_CORRECT_2026-02-17.ics"
    },
    {
        "bid_id": "RCOC 7790",
        "name": "Prefabricated Traffic Signs (109 items)",
        "deadline": datetime(2026, 2, 17, 14, 30),  # 2:30 PM EST
        "value": "$30K-$50K",
        "profit": "$27K+",
        "status": "Awaiting supplier quotes",
        "buyer": "Tracy McDonald (248-858-4796)",
        "platform": "BidNet Direct (MITN)",
        "filename": "rcoc_7790_traffic_signs_CORRECT_2026-02-17.ics"
    },
]


def generate_ics_file(bid_info, output_dir):
    """
    Generate a properly formatted .ics calendar file
    """
    deadline = bid_info['deadline']
    
    # Format deadline for iCal (YYYYMMDDTHHMMSS)
    # EST is UTC-5, so 2:30 PM EST = 19:30 UTC
    dtstart = deadline.strftime('%Y%m%dT%H%M%S')
    dtend = (deadline + timedelta(hours=1)).strftime('%Y%m%dT%H%M%S')
    dtstamp = datetime.now().strftime('%Y%m%dT%H%M%SZ')
    
    # Create unique UID
    uid = f"{bid_info['bid_id'].lower().replace(' ', '-')}-{deadline.strftime('%Y%m%d')}@nexus.deedavis.biz"
    
    # Build description
    description = f"""🚨 CRITICAL BID DEADLINE - VERIFIED

Bid: {bid_info['bid_id']} - {bid_info['name']}
Value: {bid_info['value']}
Expected Profit: {bid_info['profit']}
Status: {bid_info['status']}

Buyer: {bid_info['buyer']}
Platform: {bid_info['platform']}

DEADLINE: {deadline.strftime('%A, %B %d, %Y @ %I:%M %p EST')}

⏰ SUBMIT 3 DAYS EARLY FOR SAFETY!
Recommended submission: {(deadline - timedelta(days=3)).strftime('%A, %B %d')}

ACTION ITEMS:
1. Verify all pricing 2 days before
2. Complete bid form 1 day before  
3. Final review morning of submission
4. SUBMIT at least 2 hours before deadline

🚨 This deadline was VERIFIED from official PDF solicitation.
DO NOT MISS THIS DEADLINE!

Generated by: verify_calendar_deadlines.py
Source: CRITICAL_DEADLINE_VERIFICATION_FEB_2026.md
"""
    
    # Build .ics content
    ics_content = f"""BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Dee Davis Inc//NEXUS Calendar//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:NEXUS Opportunities - VERIFIED DEADLINES
X-WR-TIMEZONE:America/Detroit

BEGIN:VEVENT
UID:{uid}
DTSTAMP:{dtstamp}
DTSTART:{dtstart}
DTEND:{dtend}
SUMMARY:🚨 BID DUE: {bid_info['bid_id']} - {bid_info['name']} ({bid_info['value']})
DESCRIPTION:{description}
LOCATION:{bid_info['platform']}
STATUS:CONFIRMED
PRIORITY:9
BEGIN:VALARM
TRIGGER:-P3D
ACTION:DISPLAY
DESCRIPTION:🚨 {bid_info['bid_id']} bid due in 3 DAYS - Start final prep!
END:VALARM
BEGIN:VALARM
TRIGGER:-P1D
ACTION:DISPLAY
DESCRIPTION:🚨 {bid_info['bid_id']} bid due TOMORROW @ 2:30 PM - Final review!
END:VALARM
BEGIN:VALARM
TRIGGER:-PT4H
ACTION:DISPLAY
DESCRIPTION:🚨 URGENT: {bid_info['bid_id']} bid due in 4 HOURS!
END:VALARM
BEGIN:VALARM
TRIGGER:-PT2H
ACTION:DISPLAY
DESCRIPTION:🚨 CRITICAL: {bid_info['bid_id']} bid due in 2 HOURS - SUBMIT NOW!
END:VALARM
END:VEVENT

END:VCALENDAR
"""
    
    # Write file
    filepath = os.path.join(output_dir, bid_info['filename'])
    with open(filepath, 'w') as f:
        f.write(ics_content)
    
    return filepath


def main():
    print("=" * 70)
    print("🔧 FIXING CALENDAR DEADLINES")
    print("=" * 70)
    print()
    
    calendars_dir = "/Users/deedavis/NEXUS BACKEND/calendars"
    
    print(f"Output directory: {calendars_dir}")
    print(f"Generating {len(VERIFIED_BIDS)} corrected calendar files...")
    print()
    
    created_files = []
    
    for bid_info in VERIFIED_BIDS:
        print(f"📅 {bid_info['bid_id']}: {bid_info['name']}")
        print(f"   Deadline: {bid_info['deadline'].strftime('%A, %B %d, %Y @ %I:%M %p EST')}")
        print(f"   Value: {bid_info['value']}")
        
        filepath = generate_ics_file(bid_info, calendars_dir)
        created_files.append(filepath)
        
        print(f"   ✅ Created: {os.path.basename(filepath)}")
        print()
    
    print("=" * 70)
    print("✅ CALENDAR FIX COMPLETE")
    print("=" * 70)
    print()
    print(f"Created {len(created_files)} corrected calendar files:")
    for filepath in created_files:
        print(f"  • {os.path.basename(filepath)}")
    
    print()
    print("🎯 NEXT STEPS:")
    print("  1. Import these new .ics files into your calendar app")
    print("  2. Delete old incorrect calendar entries")
    print("  3. Run verify_calendar_deadlines.py to confirm")
    print("  4. Set up calendar sync to phone/email")
    print()
    print("⚠️  CRITICAL: These deadlines are VERIFIED from official PDFs!")
    print("   Trust these over any other source.")
    print()


if __name__ == "__main__":
    main()
