"""
JETA_Documents Airtable field names — canonical snake_case (see workspace schema).
Reads fall back to legacy Title Case where older bases still use them.
"""
from __future__ import annotations

from typing import Any, List, Optional, Tuple


class JDoc:
    """Canonical Airtable field names on JETA_Documents (snake_case)."""

    deal_id = 'deal_id'
    buyer_id = 'buyer_id'
    seller_id = 'seller_id'
    document_type = 'document_type'
    document_name = 'document_name'
    icc_compliant = 'icc_compliant'
    afsma_aligned = 'afsma_aligned'
    generated_date = 'generated_date'
    generated_by = 'generated_by'
    party_1_name = 'party_1_name'
    party_1_entity = 'party_1_entity'
    party_2_name = 'party_2_name'
    party_2_entity = 'party_2_entity'
    deal_description = 'deal_description'
    fee_per_gallon = 'fee_per_gallon'
    volume_gallons = 'volume_gallons'
    jeta_percentage = 'jeta_percentage'
    sent_date = 'sent_date'
    sent_to = 'sent_to'
    signed_status = 'signed_status'
    signed_date = 'signed_date'
    expiry_date = 'expiry_date'
    pdf_link = 'pdf_link'
    notes = 'notes'
    escalation_clause_version = 'escalation_clause_version'


_LEGACY: dict[str, Tuple[str, ...]] = {
    JDoc.deal_id: ('Deal',),
    JDoc.buyer_id: ('Buyer',),
    JDoc.seller_id: ('Seller',),
    JDoc.document_type: ('Document Type',),
    JDoc.document_name: ('Document Name',),
    JDoc.icc_compliant: ('ICC Compliant', 'ICC 769E Compliant'),
    JDoc.afsma_aligned: ('AFSMA Aligned',),
    JDoc.generated_date: ('Generated Date',),
    JDoc.generated_by: ('Generated By',),
    JDoc.party_1_name: ('Party 1 Name',),
    JDoc.party_1_entity: ('Party 1 Entity',),
    JDoc.party_2_name: ('Party 2 Name',),
    JDoc.party_2_entity: ('Party 2 Entity',),
    JDoc.deal_description: ('Deal Description',),
    JDoc.fee_per_gallon: ('Fee Per Gallon',),
    JDoc.volume_gallons: ('Volume Gallons',),
    JDoc.jeta_percentage: ('JETA Percentage', 'IMFPA Percentage'),
    JDoc.sent_date: ('Sent Date',),
    JDoc.sent_to: ('Sent To',),
    JDoc.signed_status: ('Signed Status',),
    JDoc.signed_date: ('Signed Date',),
    JDoc.expiry_date: ('Expiry Date',),
    JDoc.pdf_link: ('Download URL', 'PDF Link'),
    JDoc.notes: ('Notes',),
    JDoc.escalation_clause_version: ('Escalation Clause Version',),
}


def _jdoc_keys(canonical: str) -> tuple:
    leg = _LEGACY.get(canonical, ())
    return (canonical,) + leg


def jdoc_get_raw(f: dict, canonical: str) -> Any:
    for k in _jdoc_keys(canonical):
        if k in f:
            return f.get(k)
    return None


def jdoc_get_str(f: dict, canonical: str) -> str:
    for k in _jdoc_keys(canonical):
        if k not in f:
            continue
        v = f[k]
        if v is None:
            continue
        if isinstance(v, (int, float)):
            s = str(int(v) if isinstance(v, float) and v == int(v) else v)
        else:
            s = str(v).strip()
        if s == '':
            continue
        return s
    return ''


def jdoc_get_float(f: dict, canonical: str) -> Optional[float]:
    for k in _jdoc_keys(canonical):
        if k not in f or f[k] is None or f[k] == '':
            continue
        try:
            return float(f[k])
        except (TypeError, ValueError):
            continue
    return None


def jdoc_get_bool(f: dict, canonical: str) -> Optional[bool]:
    for k in _jdoc_keys(canonical):
        if k not in f or f[k] is None:
            continue
        v = f[k]
        if isinstance(v, bool):
            return v
        if isinstance(v, (int, float)):
            return bool(v)
        s = str(v).strip().lower()
        if s in ('yes', 'true', '1', 'y'):
            return True
        if s in ('no', 'false', '0', 'n'):
            return False
    return None


def jdoc_link_ids(f: dict, canonical: str) -> List[str]:
    raw = jdoc_get_raw(f, canonical)
    if raw is None:
        return []
    if isinstance(raw, list):
        return [str(x) for x in raw if x]
    return []


def jdoc_first_link_id(f: dict, canonical: str) -> str:
    ids = jdoc_link_ids(f, canonical)
    return ids[0] if ids else ''


def jdoc_pdf_path_local(f: dict) -> str:
    """Legacy local filename under GENERATED_JETA_DOCUMENTS."""
    return str(f.get('PDF Path') or '').strip()
