"""
One-Time Company Information Setup
Fill this out ONCE and all future letters auto-populate!
"""

import os
from pathlib import Path

# =============================================================================
# FILL OUT YOUR COMPANY INFORMATION HERE (ONE TIME ONLY)
# =============================================================================

COMPANY_INFO = {
    # Basic Company Information
    'COMPANY_NAME': 'Dee Davis, Inc.',
    'CONTACT_NAME': 'Dee Davis',
    'CONTACT_TITLE': 'President',
    'CONTACT_EMAIL': 'dee@deedavisinc.com',  # ← CHANGE THIS
    'CONTACT_PHONE': '(555) 123-4567',  # ← CHANGE THIS
    
    # Government Registration
    'CAGE_CODE': 'YOUR_CAGE_CODE',  # ← CHANGE THIS
    'UEI_NUMBER': 'YOUR_UEI_NUMBER',  # ← CHANGE THIS
    'DUNS_NUMBER': '',  # Optional
    
    # Certifications (comma-separated)
    'CERTIFICATIONS': 'Woman-Owned Small Business (WOSB), Service-Disabled Veteran-Owned Small Business',  # ← CUSTOMIZE THIS
    
    # GSA Schedule (if applicable)
    'GSA_SCHEDULE': '',  # ← Fill in if you have one, or leave blank
    
    # Business Description
    'BUSINESS_DESCRIPTION': '''certified diverse small business enterprise with extensive experience in medical supply procurement and distribution. We specialize in providing high-quality healthcare products to government agencies and healthcare facilities, with a particular focus on preventive health and family planning supplies.''',
    
    # Company Address
    'COMPANY_ADDRESS_LINE1': '123 Main Street',  # ← CHANGE THIS
    'COMPANY_ADDRESS_LINE2': 'Suite 100',  # ← Optional
    'COMPANY_CITY': 'Your City',  # ← CHANGE THIS
    'COMPANY_STATE': 'ST',  # ← CHANGE THIS
    'COMPANY_ZIP': '12345',  # ← CHANGE THIS
    
    # Website
    'COMPANY_WEBSITE': 'www.deedavisinc.com',  # ← CHANGE THIS
}

# =============================================================================
# AUTO-SETUP CODE (Don't modify below this line)
# =============================================================================

def save_to_env():
    """Save company info to .env file"""
    env_path = Path(__file__).parent / '.env'
    
    # Read existing .env
    existing_lines = []
    if env_path.exists():
        with open(env_path, 'r') as f:
            existing_lines = f.readlines()
    
    # Remove old company info lines
    filtered_lines = [line for line in existing_lines 
                     if not any(key in line for key in COMPANY_INFO.keys())]
    
    # Add company info section
    with open(env_path, 'w') as f:
        # Write existing lines first
        f.writelines(filtered_lines)
        
        # Add company info section
        f.write('\n# =============================================================================\n')
        f.write('# COMPANY INFORMATION (Auto-generated by setup_company_info.py)\n')
        f.write('# =============================================================================\n\n')
        
        for key, value in COMPANY_INFO.items():
            # Multi-line values need special handling
            if '\n' in str(value):
                value = value.replace('\n', ' ')
            f.write(f'{key}="{value}"\n')
    
    print("✅ Company information saved to .env file!")
    print("\nYour company info:")
    print(f"  Company: {COMPANY_INFO['COMPANY_NAME']}")
    print(f"  Contact: {COMPANY_INFO['CONTACT_NAME']}")
    print(f"  Email: {COMPANY_INFO['CONTACT_EMAIL']}")
    print(f"  Phone: {COMPANY_INFO['CONTACT_PHONE']}")
    print(f"\n🎯 All future letters will auto-populate with this information!")

def display_template():
    """Display a template letter with your info filled in"""
    print("\n" + "="*80)
    print("SAMPLE LETTER WITH YOUR INFORMATION")
    print("="*80 + "\n")
    
    template = f"""**Date:** [Auto-filled with current date]

**To:** [Officer Name from opportunity]
**Email:** [Officer Email from opportunity]
**Re:** [Opportunity Title]
**Solicitation:** [Solicitation Number]

---

Dear [Officer Name],

I am writing to introduce **{COMPANY_INFO['COMPANY_NAME']}** and express our 
strong interest in providing [products/services] for your facility's requirements.

**Company Overview:**

{COMPANY_INFO['COMPANY_NAME']} is a {COMPANY_INFO['BUSINESS_DESCRIPTION']}

**Our Qualifications:**

- **Diverse Certification:** {COMPANY_INFO['CERTIFICATIONS']}"""
    
    if COMPANY_INFO['GSA_SCHEDULE']:
        template += f"\n- **GSA Schedule:** {COMPANY_INFO['GSA_SCHEDULE']}"
    
    template += f"""
- **Quality Assurance:** We source only FDA-approved products from reputable manufacturers
- **Reliable Supply Chain:** Established relationships with multiple distributors
- **Competitive Pricing:** Volume purchasing power allows cost-effective solutions
- **Proven Track Record:** History of successful government contracts

[... rest of letter auto-generated based on opportunity ...]

**Contact Information:**

**Company:** {COMPANY_INFO['COMPANY_NAME']}
**Point of Contact:** {COMPANY_INFO['CONTACT_NAME']}, {COMPANY_INFO['CONTACT_TITLE']}
**Email:** {COMPANY_INFO['CONTACT_EMAIL']}
**Phone:** {COMPANY_INFO['CONTACT_PHONE']}
**CAGE Code:** {COMPANY_INFO['CAGE_CODE']}
**UEI/SAM Registration:** {COMPANY_INFO['UEI_NUMBER']}

Respectfully,

{COMPANY_INFO['CONTACT_NAME']}
{COMPANY_INFO['CONTACT_TITLE']}
{COMPANY_INFO['COMPANY_NAME']}
"""
    
    print(template)
    print("\n" + "="*80)
    print("✅ This is what your auto-generated letters will look like!")
    print("="*80 + "\n")

if __name__ == "__main__":
    print("🏢 DEE DAVIS INC - COMPANY INFORMATION SETUP")
    print("="*80)
    print("\n1. Edit this file (setup_company_info.py)")
    print("2. Fill in your company information at the top")
    print("3. Run this script again")
    print("4. All future letters auto-populate!\n")
    
    # Check if user has filled in the info
    needs_setup = (
        'YOUR_CAGE_CODE' in COMPANY_INFO['CAGE_CODE'] or
        '(555) 123-4567' in COMPANY_INFO['CONTACT_PHONE'] or
        'dee@deedavisinc.com' in COMPANY_INFO['CONTACT_EMAIL']
    )
    
    if needs_setup:
        print("⚠️  SETUP REQUIRED:")
        print("    Please fill in your actual company information in this file first.")
        print("    Look for the '← CHANGE THIS' comments at the top of the file.\n")
        print("Then run: python setup_company_info.py\n")
    else:
        save_to_env()
        display_template()
        print("\n🎉 READY! Run this to generate letters with your info:")
        print("    python contracting_officer_outreach.py\n")
