#!/usr/bin/env python3
"""
vertex_automation.py — VERTEX Auto-Trigger Layer

Every NEXUS module fires VERTEX actions automatically on key events.
No manual invoice or revenue record creation needed.

Event API:
    from vertex_automation import vertex_auto_trigger
    vertex_auto_trigger('gpss.opportunity.won', source_record_id='recXXX', data={...})

All triggers are logged to VERTEX REPORTS for audit trail.

Event types:
    gpss.opportunity.won          → Invoice schedule + AP records + WAWF if federal
    gpss.opportunity.lost         → Cancel draft invoices
    atlas.milestone.complete      → Milestone invoice
    atlas.expense.logged          → VERTEX EXPENSE record
    prism.service.complete        → Service invoice from rate table
    prism.drug_test.collected     → Queue test invoice (batch daily)
    ddcss.client.won              → Consulting/service invoice
    compass.qa.passed             → Release held invoice
    compass.qa.failed             → Flag + hold invoice
    gbis.grant.awarded            → Revenue record + expense tracking setup
    lbpc.recovery.complete        → Contingency fee invoice (30%)
    nemt.trip.complete            → Delegated to nemt_billing.generate_claim()
    fleetflow.delivery.confirmed  → Freight/logistics invoice
    shield.service.verified       → SHIELD service invoice (Medicaid CHW billing)
    shield.time.verified          → Navigator time-based invoice (15-min units)
    shield.billing.approved       → Move invoice Pending Approval → Ready to Submit
"""

import json
import logging
import os
from datetime import datetime, timedelta
from typing import Any, Dict, Optional

from dotenv import load_dotenv

load_dotenv()

log = logging.getLogger("vertex_automation")
if not log.handlers:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [vertex_automation] %(levelname)s %(message)s",
    )


# ---------------------------------------------------------------------------
# Lazy imports to avoid circular dependencies
# ---------------------------------------------------------------------------

def _airtable():
    from nexus_backend import AirtableClient
    return AirtableClient()


def _vi():
    """Return VI field map without importing all of api_server at module load."""
    from api_server import VI
    return VI


def _vr():
    from api_server import VR
    return VR


def _ve():
    from api_server import VE
    return VE


def _vap():
    from api_server import VAP
    return VAP


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _now_date() -> str:
    return datetime.now().date().isoformat()


def _due_date(days: int = 30) -> str:
    return (datetime.now().date() + timedelta(days=days)).isoformat()


def _inv_number(prefix: str = "INV") -> str:
    return f"{prefix}-{datetime.now().strftime('%Y%m%d-%H%M%S')}"


def _log_to_vertex_reports(
    event_type: str,
    source_system: str,
    source_record_id: str,
    outcome: str,
    detail: str,
    airtable=None,
):
    """Write an audit entry to VERTEX REPORTS."""
    try:
        at = airtable or _airtable()
        at.create_record("VERTEX REPORTS", {
            "REPORT DATE":     _now_date(),
            "REPORT TYPE":     "Auto-Trigger Event",
            "SOURCE SYSTEM":   source_system,
            "SOURCE RECORD":   source_record_id,
            "EVENT TYPE":      event_type,
            "OUTCOME":         outcome,
            "DETAILS":         detail[:5000],
            "GENERATED BY":    "vertex_automation.py",
        })
    except Exception as ex:
        log.warning(f"Could not write to VERTEX REPORTS: {ex}")


# ---------------------------------------------------------------------------
# Event Handlers
# ---------------------------------------------------------------------------

def _handle_gpss_opportunity_won(source_record_id: str, data: Dict, at) -> Dict:
    """
    Contract won:
    - Create a client invoice (or recurring template for service contracts)
    - Create AP record for each sub if sub cost is provided
    - Mark WAWF required if federal
    """
    VI = _vi(); VR = _vr(); VAP = _vap()

    agency        = data.get("agency_name", "")
    title         = data.get("title", "")
    value         = float(data.get("contract_value", 0) or 0)
    contract_num  = data.get("contract_number", "")
    is_federal    = data.get("is_federal", False)
    is_service    = data.get("is_service_contract", False)
    sub_cost      = float(data.get("sub_cost", 0) or 0)
    sub_name      = data.get("sub_name", "")
    payment_terms = data.get("payment_terms", "Net 30")

    created = {}

    if value > 0:
        inv_fields = {
            VI["invoice_number"]:  _inv_number("INV"),
            VI["invoice_date"]:    _now_date(),
            VI["due_date"]:        _due_date(30),
            VI["client_name"]:     agency,
            VI["source_system"]:   "GPSS",
            VI["source_record"]:   source_record_id,
            VI["invoice_type"]:    "Service Contract" if is_service else "Standard",
            VI["total_amount"]:    value,
            VI["payment_status"]:  "Unpaid",
            VI["payment_terms"]:   payment_terms,
            VI["notes"]:           f"Auto-generated on contract award: {title}",
            VI["contract_number"]: contract_num,
            VI["government_agency"]: agency,
        }
        if is_service:
            from api_server import VI_RECURRING, _FREQ_DAYS
            inv_fields[VI_RECURRING["recurring"]]           = True
            inv_fields[VI_RECURRING["recurring_frequency"]] = "Monthly"
            inv_fields[VI_RECURRING["next_invoice_date"]]   = _due_date(30)
        if is_federal:
            inv_fields[VI.get("wawf_status", "WAWF STATUS")] = "Not Submitted"

        invoice = at.create_record("VERTEX INVOICES", inv_fields)
        created["invoice"] = invoice.get("id")
        log.info(f"[GPSS Won] Invoice created: {invoice.get('id')} for ${value:,.2f}")

    # AP record for sub if sub cost provided
    if sub_cost > 0 and sub_name:
        ap_fields = {
            VAP["bill_number"]:    _inv_number("AP"),
            VAP["bill_date"]:      _now_date(),
            VAP["due_date"]:       _due_date(30),
            VAP["vendor_name"]:    sub_name,
            VAP["source_system"]:  "GPSS",
            VAP["source_record"]:  source_record_id,
            VAP["category"]:       "Sub Labor",
            VAP["description"]:    f"Subcontractor cost for: {title}",
            VAP["total_amount"]:   sub_cost,
            VAP["payment_status"]: "Unpaid",
            VAP["payment_terms"]:  "Net 30",
            VAP["contract_number"]: contract_num,
        }
        ap = at.create_record("VERTEX ACCOUNTS PAYABLE", ap_fields)
        created["ap_bill"] = ap.get("id")
        log.info(f"[GPSS Won] AP bill created: {ap.get('id')} for sub ${sub_cost:,.2f}")

    return created


def _handle_gpss_opportunity_lost(source_record_id: str, data: Dict, at) -> Dict:
    """Cancel any Unpaid invoices tied to this opportunity."""
    VI = _vi()
    formula = f"AND({{{VI['source_record']}}}='{source_record_id}',{{{VI['payment_status']}}}='Unpaid')"
    try:
        invoices = at.search_records("VERTEX INVOICES", formula)
        cancelled = []
        for inv in invoices:
            at.update_record("VERTEX INVOICES", inv["id"], {
                VI["payment_status"]: "Cancelled",
                VI["notes"]: (inv.get("fields", {}).get(VI["notes"], "") or "") + " | Auto-cancelled: opportunity lost",
            })
            cancelled.append(inv["id"])
        log.info(f"[GPSS Lost] Cancelled {len(cancelled)} draft invoices")
        return {"cancelled_invoices": cancelled}
    except Exception as e:
        log.error(f"[GPSS Lost] Error cancelling invoices: {e}")
        return {"error": str(e)}


def _handle_atlas_milestone_complete(source_record_id: str, data: Dict, at) -> Dict:
    """Generate milestone invoice when a project milestone is marked complete."""
    VI = _vi()
    client_name   = data.get("client_name", "")
    milestone     = data.get("milestone_name", "")
    amount        = float(data.get("milestone_amount", 0) or 0)
    project_id    = data.get("project_id", source_record_id)
    contract_num  = data.get("contract_number", "")

    if amount <= 0:
        return {"skipped": "No milestone amount provided"}

    inv_fields = {
        VI["invoice_number"]:  _inv_number("MLSTN"),
        VI["invoice_date"]:    _now_date(),
        VI["due_date"]:        _due_date(30),
        VI["client_name"]:     client_name,
        VI["source_system"]:   "ATLAS",
        VI["source_record"]:   project_id,
        VI["invoice_type"]:    "Milestone",
        VI["total_amount"]:    amount,
        VI["payment_status"]:  "Unpaid",
        VI["payment_terms"]:   "Net 30",
        VI["contract_number"]: contract_num,
        VI["notes"]:           f"Milestone invoice: {milestone}",
    }
    invoice = at.create_record("VERTEX INVOICES", inv_fields)
    log.info(f"[ATLAS Milestone] Invoice created: {invoice.get('id')} — {milestone} ${amount:,.2f}")
    return {"invoice": invoice.get("id")}


def _handle_atlas_expense_logged(source_record_id: str, data: Dict, at) -> Dict:
    """Create a VERTEX EXPENSE when a project expense is logged in ATLAS."""
    VE = _ve()
    exp_fields = {
        VE["expense_date"]:   data.get("expense_date", _now_date()),
        VE["vendor_payee"]:   data.get("vendor", ""),
        VE["description"]:    data.get("description", ""),
        VE["category"]:       data.get("category", "Project Expense"),
        VE["amount"]:         float(data.get("amount", 0) or 0),
        VE["payment_method"]: data.get("payment_method", "Credit Card"),
        VE["payment_status"]: "Paid",
        VE["billable"]:       data.get("billable", True),
        VE["notes"]:          f"ATLAS Project: {source_record_id}",
    }
    expense = at.create_record("VERTEX EXPENSES", exp_fields)
    log.info(f"[ATLAS Expense] Created: {expense.get('id')} ${data.get('amount', 0):,.2f}")
    return {"expense": expense.get("id")}


def _handle_prism_service_complete(source_record_id: str, data: Dict, at) -> Dict:
    """Auto-invoice for a completed PRISM field service (drug test, fingerprint, DNA, notary)."""
    VI = _vi()
    client_name  = data.get("client_name", "")
    service_type = data.get("service_type", "Field Service")
    amount       = float(data.get("amount", 0) or 0)
    hcpcs        = data.get("hcpcs_code", "")

    if amount <= 0:
        return {"skipped": "No service amount"}

    line_item = json.dumps([{
        "description": service_type,
        "hcpcs": hcpcs,
        "quantity": 1,
        "rate": amount,
        "amount": amount,
    }])

    inv_fields = {
        VI["invoice_number"]:  _inv_number("PRISM"),
        VI["invoice_date"]:    _now_date(),
        VI["due_date"]:        _due_date(30),
        VI["client_name"]:     client_name,
        VI["source_system"]:   "PRISM",
        VI["source_record"]:   source_record_id,
        VI["invoice_type"]:    "Service",
        VI["line_items"]:      line_item,
        VI["subtotal"]:        amount,
        VI["total_amount"]:    amount,
        VI["payment_status"]:  "Unpaid",
        VI["payment_terms"]:   "Net 30",
        VI["notes"]:           f"PRISM service: {service_type} | Order ID: {source_record_id}",
    }
    invoice = at.create_record("VERTEX INVOICES", inv_fields)
    log.info(f"[PRISM Service] Invoice: {invoice.get('id')} — {service_type} ${amount:,.2f}")
    return {"invoice": invoice.get("id")}


def _handle_ddcss_client_won(source_record_id: str, data: Dict, at) -> Dict:
    """Auto-invoice consulting/service fee when a corporate client is won in DDCSS."""
    VI = _vi()
    company_name  = data.get("company_name", "")
    service_desc  = data.get("service_description", "Consulting & Management Services")
    amount        = float(data.get("monthly_value", 0) or data.get("contract_value", 0) or 0)
    is_recurring  = data.get("is_recurring", True)

    if amount <= 0:
        return {"skipped": "No contract value"}

    inv_fields = {
        VI["invoice_number"]:  _inv_number("DDCSS"),
        VI["invoice_date"]:    _now_date(),
        VI["due_date"]:        _due_date(30),
        VI["client_name"]:     company_name,
        VI["source_system"]:   "DDCSS",
        VI["source_record"]:   source_record_id,
        VI["invoice_type"]:    "Standard",
        VI["total_amount"]:    amount,
        VI["payment_status"]:  "Unpaid",
        VI["payment_terms"]:   "Net 30",
        VI["notes"]:           service_desc,
    }
    if is_recurring:
        from api_server import VI_RECURRING
        inv_fields[VI_RECURRING["recurring"]]           = True
        inv_fields[VI_RECURRING["recurring_frequency"]] = "Monthly"
        inv_fields[VI_RECURRING["next_invoice_date"]]   = _due_date(30)

    invoice = at.create_record("VERTEX INVOICES", inv_fields)
    log.info(f"[DDCSS Won] Invoice: {invoice.get('id')} — {company_name} ${amount:,.2f}")
    return {"invoice": invoice.get("id")}


def _handle_gbis_grant_awarded(source_record_id: str, data: Dict, at) -> Dict:
    """Log grant award as revenue and set up expense tracking."""
    VR = _vr(); VE = _ve()
    grant_name  = data.get("grant_name", "")
    funder      = data.get("funder_name", "")
    amount      = float(data.get("grant_amount", 0) or 0)
    start_date  = data.get("performance_start", _now_date())

    created = {}

    if amount > 0:
        rev = at.create_record("VERTEX REVENUE", {
            VR["revenue_date"]:   _now_date(),
            VR["source"]:         funder,
            VR["revenue_type"]:   "Grant Award",
            VR["source_system"]:  "GBIS",
            VR["amount"]:         amount,
            VR["taxable"]:        False,
            VR["recurring"]:      False,
            VR["notes"]:          f"Grant: {grant_name} | Opp: {source_record_id}",
        })
        created["revenue"] = rev.get("id")
        log.info(f"[GBIS Grant] Revenue record: {rev.get('id')} ${amount:,.2f}")

    return created


def _handle_lbpc_recovery_complete(source_record_id: str, data: Dict, at) -> Dict:
    """Auto-invoice 30% contingency fee when a surplus recovery is complete."""
    VI = _vi()
    client_name    = data.get("client_name", "")
    recovery_value = float(data.get("recovery_value", 0) or 0)
    fee_pct        = float(data.get("fee_percent", 30))
    fee_amount     = round(recovery_value * fee_pct / 100, 2)

    if fee_amount <= 0:
        return {"skipped": "No recovery value"}

    inv_fields = {
        VI["invoice_number"]:  _inv_number("LBPC"),
        VI["invoice_date"]:    _now_date(),
        VI["due_date"]:        _due_date(30),
        VI["client_name"]:     client_name,
        VI["source_system"]:   "LBPC",
        VI["source_record"]:   source_record_id,
        VI["invoice_type"]:    "Contingency Fee",
        VI["total_amount"]:    fee_amount,
        VI["payment_status"]:  "Unpaid",
        VI["payment_terms"]:   "Due on Receipt",
        VI["notes"]:           f"Contingency fee {fee_pct}% on ${recovery_value:,.2f} surplus recovery",
    }
    invoice = at.create_record("VERTEX INVOICES", inv_fields)
    log.info(f"[LBPC Recovery] Fee invoice: {invoice.get('id')} ${fee_amount:,.2f}")
    return {"invoice": invoice.get("id")}


def _handle_fleetflow_delivery_confirmed(source_record_id: str, data: Dict, at) -> Dict:
    """Auto-invoice freight/logistics charges when a delivery is confirmed."""
    VI = _vi()
    client_name  = data.get("client_name", "")
    amount       = float(data.get("freight_amount", 0) or 0)
    description  = data.get("description", "Freight / Logistics Services")

    if amount <= 0:
        return {"skipped": "No freight amount"}

    inv_fields = {
        VI["invoice_number"]:  _inv_number("FLTFL"),
        VI["invoice_date"]:    _now_date(),
        VI["due_date"]:        _due_date(30),
        VI["client_name"]:     client_name,
        VI["source_system"]:   "Other",
        VI["source_record"]:   source_record_id,
        VI["invoice_type"]:    "Standard",
        VI["total_amount"]:    amount,
        VI["payment_status"]:  "Unpaid",
        VI["payment_terms"]:   "Net 30",
        VI["notes"]:           description,
    }
    invoice = at.create_record("VERTEX INVOICES", inv_fields)
    log.info(f"[FleetFlow] Freight invoice: {invoice.get('id')} ${amount:,.2f}")
    return {"invoice": invoice.get("id")}


def _handle_compass_qa_passed(source_record_id: str, data: Dict, at) -> Dict:
    """Release a held invoice when QA check passes."""
    VI = _vi()
    invoice_id = data.get("invoice_id", "")
    if not invoice_id:
        return {"skipped": "No invoice_id provided"}
    at.update_record("VERTEX INVOICES", invoice_id, {
        VI["payment_status"]: "Unpaid",
        VI["notes"]: (data.get("existing_notes", "") or "") + " | QA passed — released for sending",
    })
    log.info(f"[COMPASS QA Pass] Invoice {invoice_id} released")
    return {"released": invoice_id}


def _handle_compass_qa_failed(source_record_id: str, data: Dict, at) -> Dict:
    """Flag and hold an invoice when QA check fails."""
    VI = _vi()
    invoice_id = data.get("invoice_id", "")
    reason     = data.get("reason", "QA check failed")
    if not invoice_id:
        return {"skipped": "No invoice_id provided"}
    at.update_record("VERTEX INVOICES", invoice_id, {
        VI["payment_status"]: "On Hold",
        VI["notes"]: (data.get("existing_notes", "") or "") + f" | HELD: {reason}",
    })
    log.info(f"[COMPASS QA Fail] Invoice {invoice_id} held — {reason}")
    return {"held": invoice_id}


def _handle_shield_service_verified(source_record_id: str, data: Dict, at) -> Dict:
    """Create a VERTEX invoice when a SHIELD service is verified complete."""
    VI = _vi()

    service_line = data.get("service_line", "SHIELD Service")
    family_name = data.get("family_name", "")
    case_number = data.get("case_number", "")
    county = data.get("county", "")
    service_amount = float(data.get("service_amount", 0) or 0)
    admin_fee_rate = float(data.get("admin_fee_rate", 0.225) or 0.225)
    admin_fee = round(service_amount * admin_fee_rate, 2)
    total = round(service_amount + admin_fee, 2)
    cpt_code = data.get("cpt_code", "")
    billing_type = data.get("billing_type", "Medicaid CHW")
    payer = data.get("payer", "Michigan Medicaid")
    navigator_name = data.get("navigator_name", "")

    line_items = json.dumps([
        {"description": f"{service_line} — {family_name} family ({case_number})", "amount": service_amount, "cpt": cpt_code},
        {"description": f"DDI Admin Fee ({admin_fee_rate*100:.1f}%)", "amount": admin_fee},
    ])

    inv_fields = {
        VI["invoice_number"]: _inv_number("SHD"),
        VI["invoice_date"]: _now_date(),
        VI["due_date"]: _due_date(30),
        VI["client_name"]: payer,
        VI["source_system"]: "SHIELD",
        VI["source_record"]: source_record_id,
        VI["invoice_type"]: billing_type,
        VI["line_items"]: line_items,
        VI["subtotal"]: service_amount,
        VI["total_amount"]: total,
        VI["payment_status"]: "Pending Approval",
        VI["payment_terms"]: "Net 30",
        VI["notes"]: f"SHIELD service: {service_line} | Case #{case_number} | {county} County | Navigator: {navigator_name} | CPT: {cpt_code} | Verified Complete — awaiting supervisor approval",
    }

    invoice = at.create_record("VERTEX INVOICES", inv_fields)
    log.info(f"[SHIELD Verified] Invoice created: {invoice.get('id')} for ${total:,.2f} ({service_line})")
    return {"invoice": invoice.get("id"), "total": total}


def _handle_shield_time_verified(source_record_id: str, data: Dict, at) -> Dict:
    """Create a VERTEX invoice for verified navigator time billing."""
    VI = _vi()

    navigator_name = data.get("navigator_name", "")
    case_number = data.get("case_number", "")
    duration_minutes = int(data.get("duration_minutes", 0) or 0)
    cpt_code = data.get("cpt_code", "98960")
    billing_type = data.get("billing_type", "Medicaid CHW")
    rate_per_unit = float(data.get("rate_per_unit", 25.0) or 25.0)
    units = max(1, duration_minutes // 15)
    service_amount = round(rate_per_unit * units, 2)
    admin_fee = round(service_amount * 0.225, 2)
    total = round(service_amount + admin_fee, 2)

    line_items = json.dumps([
        {"description": f"CHW Navigation — {navigator_name} ({duration_minutes} min / {units} units @ ${rate_per_unit}/unit)", "amount": service_amount, "cpt": cpt_code},
        {"description": "DDI Admin Fee (22.5%)", "amount": admin_fee},
    ])

    inv_fields = {
        VI["invoice_number"]: _inv_number("SHD-T"),
        VI["invoice_date"]: _now_date(),
        VI["due_date"]: _due_date(30),
        VI["client_name"]: data.get("payer", "Michigan Medicaid"),
        VI["source_system"]: "SHIELD",
        VI["source_record"]: source_record_id,
        VI["invoice_type"]: billing_type,
        VI["line_items"]: line_items,
        VI["subtotal"]: service_amount,
        VI["total_amount"]: total,
        VI["payment_status"]: "Pending Approval",
        VI["notes"]: f"Navigator time: {navigator_name} | Case #{case_number} | CPT {cpt_code} | {duration_minutes} min ({units} units)",
    }

    invoice = at.create_record("VERTEX INVOICES", inv_fields)
    log.info(f"[SHIELD Time] Invoice created: {invoice.get('id')} for ${total:,.2f} ({navigator_name})")
    return {"invoice": invoice.get("id"), "total": total, "units": units}


def _handle_shield_billing_approved(source_record_id: str, data: Dict, at) -> Dict:
    """Move a VERTEX invoice from Pending Approval to Ready to Submit."""
    VI = _vi()
    invoice_id = data.get("vertex_invoice_id", "")
    supervisor = data.get("supervisor_name", "")
    if not invoice_id:
        return {"skipped": "No vertex_invoice_id provided"}
    at.update_record("VERTEX INVOICES", invoice_id, {
        VI["payment_status"]: "Ready to Submit",
        VI["notes"]: (data.get("existing_notes", "") or "") + f" | APPROVED by {supervisor} on {_now_date()}",
    })
    log.info(f"[SHIELD Approved] Invoice {invoice_id} approved by {supervisor}")
    return {"approved": invoice_id}


# ---------------------------------------------------------------------------
# Event Router — the single public entry point
# ---------------------------------------------------------------------------

_EVENT_HANDLERS = {
    "gpss.opportunity.won":          _handle_gpss_opportunity_won,
    "gpss.opportunity.lost":         _handle_gpss_opportunity_lost,
    "atlas.milestone.complete":      _handle_atlas_milestone_complete,
    "atlas.expense.logged":          _handle_atlas_expense_logged,
    "prism.service.complete":        _handle_prism_service_complete,
    "ddcss.client.won":              _handle_ddcss_client_won,
    "gbis.grant.awarded":            _handle_gbis_grant_awarded,
    "lbpc.recovery.complete":        _handle_lbpc_recovery_complete,
    "fleetflow.delivery.confirmed":  _handle_fleetflow_delivery_confirmed,
    "compass.qa.passed":             _handle_compass_qa_passed,
    "compass.qa.failed":             _handle_compass_qa_failed,
    "shield.service.verified":       _handle_shield_service_verified,
    "shield.time.verified":          _handle_shield_time_verified,
    "shield.billing.approved":       _handle_shield_billing_approved,
}


def vertex_auto_trigger(
    event_type: str,
    source_record_id: str = "",
    data: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Main entry point for all VERTEX auto-triggers.

    Args:
        event_type:       One of the defined event strings (e.g. 'gpss.opportunity.won')
        source_record_id: The Airtable record ID of the triggering entity
        data:             Dict with event-specific fields (agency_name, amount, etc.)

    Returns:
        Dict with outcome details, suitable for logging or returning from an API endpoint.
    """
    data = data or {}
    handler = _EVENT_HANDLERS.get(event_type)
    at = _airtable()

    if not handler:
        log.warning(f"vertex_auto_trigger: unknown event_type '{event_type}'")
        return {"error": f"Unknown event type: {event_type}"}

    source_system = event_type.split(".")[0].upper()
    try:
        result = handler(source_record_id, data, at)
        outcome = "success"
        detail  = json.dumps(result, default=str)
        log.info(f"vertex_auto_trigger OK: {event_type} → {detail[:200]}")
    except Exception as e:
        result  = {"error": str(e)}
        outcome = "error"
        detail  = str(e)
        log.error(f"vertex_auto_trigger FAILED: {event_type} — {e}")

    _log_to_vertex_reports(event_type, source_system, source_record_id, outcome, detail, at)
    return {
        "event_type":       event_type,
        "source_record_id": source_record_id,
        "outcome":          outcome,
        "result":           result,
    }
